src/controllers/DefaultController.php
<?php

namespace maerduq\usmAlbums\controllers;

use maerduq\usmAlbums\models\Album;
use yii\filters\AccessControl;

class DefaultController extends \yii\web\Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ];
    }

    public function actionIndex() {
        $albums = Album::find()->orderBy(['date' => SORT_DESC, 'id' => SORT_DESC])->all();

        return $this->render($this->module->overviewViewFile, [
            'albums' => $albums
        ]);
    }

    public function actionAlbum($id) {
        $album = Album::findOne($id);
        if ($album === null) {
            return $this->redirect(['index']);
        }

        return $this->render($this->module->albumViewFile, [
            'album' => $album
        ]);
    }

    public function actionPhoto($id, $file, $thumbnail = true) {
        $album = Album::findOne($id);
        $subDir = ($thumbnail) ? Album::DIR_THUMBNAILS : Album::DIR_PICTURES;

        $file = $album->albumPath() . $subDir . '/' . basename($file);

        header("Content-Type: " . \yii\helpers\FileHelper::getMimeTypeByExtension($file));
        flush();
        readfile($file);
        die();
    }

    public function sitemap() {
        return array_map(function ($item) {
            return ['url' => ['/photos/default/album', 'id' => $item->id]];
        }, Album::find()->all());
    }
}

src/views/admin/_form.php
<?php

use kartik\datetime\DateTimePicker;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\photos\models\Album */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="album-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'date')->widget(DateTimePicker::className(), [
        'pluginOptions' => [
            'format' => 'yyyy-mm-dd',
            'autoclose' => true,
            'startView' => 4,
            'minView' => 2,
            'maxView' => 4,
        ]
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

src/views/admin/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\modules\photos\models\Album */

$this->title = 'Create Album';
$this->params['breadcrumbs'][] = ['label' => 'Albums', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="album-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

src/views/admin/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\photos\models\AlbumSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Albums';
?>
<div class="album-index">
    <div class="content-toolbar">
        <?= Html::a('Create Album', ['create'], ['class' => 'btn btn-primary']) ?>
    </div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            'name',
            'date:date',
            'cover_photo',
            //            'created_at',
            // 'updated_at',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {photos} {update} {delete}',
                'buttons' => [
                    'photos' => function ($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-picture"></span>', ['photos', 'id' => $model->id]);
                    },
                    'view' => function ($url, $model, $key) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['default/album', 'id' => $model->id], ['target' => '_blank']);
                    },
                ]
            ],
        ],
    ]) ?>
</div>

src/views/admin/photos.php
<?php

use maerduq\usmAlbums\assets\PhotoFormAsset;
use yii\helpers\Html;
use yii\helpers\Url;

PhotoFormAsset::register($this);

/* @var $this yii\web\View */
/* @var $model app\modules\photos\models\Album */

$this->title = 'Update photos of album: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Albums', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['update', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Photos';
?>

<div class='jumbotron'>
    <h3>Upload new images</h3>

    <form id="upload" method="post" action="<?= Url::to(['upload', 'id' => $model->id]) ?>" enctype="multipart/form-data">
        <input type="file" name="files[]" multiple>
        <small>Max file size: <?= ini_get("upload_max_filesize"); ?></small>
    </form>

    <br/>
    <span id="info"></span><span id="info2"></span><span id="info3"></span>
    <div class="progress" id='progress' style='display:none'>
        <div id='pg-success' class="progress-bar progress-bar-striped"></div>
        <div id='pg-failed' class="progress-bar progress-bar-danger progress-bar-striped"></div>
    </div>
    <?= Html::a("Reload", ['photos', 'id' => $model->id], ['id' => 'refresh-button', 'style' => 'display:none', 'class' => 'btn btn-primary btn-lg']) ?>
    <div class='alert alert-danger hidden' id='fails' style='margin-top:20px;margin-bottom:0'>
        <h4>Errors</h4>
        <ul id='fails-list'></ul>
    </div>
</div>
<h3>There are <b> <span id='count'><?= count($model->photos) ?></span> photos</b> in this album</h3>

<div class='list-group'>
    <?php foreach ($model->photos as $photo): ?>
        <div class='list-group-item'>
            <a href='<?= Url::to(['default/photo', 'id' => $model->id, 'file' => $photo, 'thumbnail' => 0]) ?>' data-lightbox='set' data-title='<?= $photo ?>'>
                <img src='<?= Url::to(['default/photo', 'id' => $model->id, 'file' => $photo]) ?>' style='margin: -10px 15px -10px -15px;height:80px'/>
            </a>
            <?= $photo ?>
            <div class='pull-right' style='line-height:60px'>
                <?php if ($photo == $model->cover_photo): ?>
                    <span class="badge">Cover photo</span>
                <?php else: ?>
                    <div class='actions'>
                        <?= Html::a('Delete', ['delete-photo', 'id' => $model->id, 'file' => $photo], ['class' => 'btn btn-danger button-delete']) ?>
                        <?= Html::a('Set as cover photo', ['set-cover-photo', 'id' => $model->id, 'file' => $photo], ['class' => 'btn btn-link']) ?>
                    </div>
                <?php endif ?>
            </div>
        </div>
    <?php endforeach ?>
</div>
<style>
    .list-group-item .actions {
        display: none;
    }

    .list-group-item:hover .actions {
        display: block;
    }
</style>

src/views/admin/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\modules\photos\models\Album */

$this->title = 'Update Album: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Albums', 'url' => ['index']];
$this->params['breadcrumbs'][] = $model->name;
?>
<div class="album-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>